<?php
$fbcolorscheme	=	 Mage::getStoreConfig('facebooklike_options/all_settings/fbcolorscheme'); 

$fbappid		=	Mage::getStoreConfig('facebooklike_options/all_settings/fbappid');

$fblayout		=	Mage::getStoreConfig('facebooklike_options/all_settings/fblayout');

$fbface			=	Mage::getStoreConfig('facebooklike_options/all_settings/fbface');
	
$fblocale		= 	Mage::app()->getLocale()->getLocaleCode();

$dbdatawidth	=	Mage::getStoreConfig('facebooklike_options/all_settings/datawidth');

$fbcomments	=	Mage::getStoreConfig('facebooklike_options/all_settings/fbcomments');

if($fbface==1){

    $fbface='true';
	
    }else{

    $fbface='false';

}
$fbappid=($fbappid=='')	?	'512993528731249' : $fbappid	;//If FB APP ID is not added
$dbdatawidth=($dbdatawidth=='')	?	'450' : $dbdatawidth	;//default button width
?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=<?php echo $fbappid;?>&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php /* ?><fb:like layout="<?php echo $fblayout; ?>" show_faces="<?php echo $fbface; ?>"   width="<?php echo $dbdatawidth;?>" color_scheme="<?php echo $fbcolorscheme;?>" ></fb:like> <?php */ ?>
<?php if($fbcomments) { ?>
<div class="fb-comments" data-href="<?php echo $currentUrl; ?>"  data-numposts="5"></div>
<?php } ?>